# Makefile
#----------------------------------------------------------------------------------------
#
#  Project: CCore 4.01
#
#  License: Boost Software License - Version 1.0 - August 17th, 2003 
#
#            see http://www.boost.org/LICENSE_1_0.txt or the local copy
#
#  Copyright (c) 2022 Sergey Strukov. All rights reserved.
#
#----------------------------------------------------------------------------------------

OPT = -j 8

LIST = Aspect Book ContourLab RandomId Sample SubLab TruePrime UserPreference Zipmap 
# DDLDisplay WinLab BookLab  

include ../Target/Makefile.list

